package com.liveverse.realtime.websocket.event;

public enum EventType {
    CHAT,
    CHAT_HISTORY,
    POLL_CREATE,
    POLL_VOTE,
    POLL_CLOSE,
    POLL_ACTIVE,
    PLAYBACK_STATE_HINT,
    YOUTUBE_PLAY,
    YOUTUBE_PAUSE,
    YOUTUBE_SEEK,
    YOUTUBE_SYNC_STATE,
    ROOM_VIDEO_CHANGED,
    REACTION,
    WEBRTC_OFFER,
    WEBRTC_ANSWER,
    WEBRTC_ICE_CANDIDATE,
    PARTICIPANT_COUNT,
    ACTIVITY_LOG,
    ACTIVITY_LOG_HISTORY,
    ERROR
}
